dist: xenial
language: csharp
mono: none
dotnet: 2.2
solution: ModMail.sln

before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
script:
  - dotnet restore
  - dotnet build
after_success:
  - chmod +x success.sh
  - ./success.sh
after_failure:
  - chmod +x fail.sh
  - ./fail.sh
